name: Build & Test

on:
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '3.1.101'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      # Run dotnet build and tests
      - name: Install dependencies
        run: dotnet restore src/GreenLightHealth.sln
      - name: Build
        run: dotnet build src/GreenLightHealth.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test src/GreenLightHealth.Tests/GreenLightHealth.Tests.csproj --no-restore --verbosity normal      